AMBL=IDAAMBL                                                                    
IDAAMBL=IDAAMBL                                                                 
AMBX=IDAAMBXN                                                                   
AMB=IDAAMB                                                                      
IDAAMB=IDAAMB                                                                   
ACB=IFGACB                                                                      
IFGACB=IFGACB                                                                   
BUFC=IDABUFC                                                                    
IDABUFC                                                                         
BUFXIRBA=IDABUFC                                                                
BUFD=IDABUFDR                                                                   
RPL=IFGRPL                                                                      
IFGRPL=IFGRPL                                                                   
IDABUFDR                                                                        
CTGFL                                                                           
IXH=IDAIXH                                                                      
IDAIXH                                                                          
IDAPLHDR                                                                        
PLHID=IDAPLHDR                                                                  
PLHCNT=IDAPLHDR                                                                 
PLHELTH=IDAPLHDR                                                                
PLHDRREQ=IDAPLHDR                                                               
PLHDRMAX=IDAPLHDR                                                               
PLHDRCUR=IDAPLHDR                                                               
PLHIOSDQ=IDAPLHDR                                                               
PLH=IDAPLHD                                                                     
IDAPLHD                                                                         
IDAPLH                                                                          
IOM=IOMB                                                                        
-RPLH                                                                           
-RPLIOERR                                                                       
-RPLYAREA                                                                       
-RPLYCHAR                                                                       
-RPLYOVER                                                                       
-RPLYRJTD                                                                       
-RPLCONT                                                                        
-RPLYMOD                                                                        
-RPLACR                                                                         
-PLHEXP                                                                         
=AMBIDENT=AMBRSC                                                                
=AMBEOVMK=AMBEOVR                                                               
=AMBEOVMR=AMBEOVR                                                               
=AMBEOVAK=AMBEOVR                                                               
=AMBEOVAR=AMBEOVR                                                               
=AMBPSDS=AMBFLG0                                                                
=AMBSWSP=AMBFLG0                                                                
=AMBCREAT=AMBFLG1                                                               
=AMBTYPE=AMBFLG1                                                                
=AMBMCAT=AMBFLG1                                                                
=AMBPCAT=AMBFLG1                                                                
=AMBSPEED=AMBFLG1                                                               
=AMBUBF=AMBFLG1                                                                 
=AMBJRN=AMBFLG1                                                                 
=AMBINBUF=AMBFLG1                                                               
=AMBDORGA=AMBDSORG                                                              
=AMBCAT=AMBINFL                                                                 
=AMBSCRA=AMBINFL                                                                
=AMBUCRA=AMBINFL                                                                
=AMBUPX=AMBINFL                                                                 
=AMBSDS=AMBINFL                                                                 
=AMBOPEN=AMBOFLGS                                                               
=AMBEXFG=AMBOFLGS                                                               
=AMBBUSY=AMBOFLGS                                                               
=AMBPUG=AMBFLG2                                                                 
=AMBLSR=AMBAFLG                                                                 
=AMBGSR=AMBAFLG                                                                 
=AMBICI=AMBAFLG                                                                 
=AMBDFR=AMBAFLG                                                                 
=AMBSIS=AMBAFLG                                                                 
=AMBCFX=AMBAFLG                                                                 
=AMBLWAIT=AMBLEFLG                                                              
=AMBLESET=AMBLEFLG                                                              
=AMBLDDC=AMBLQ                                                                  
=AMBLGSR=AMBLQ                                                                  
=AMBLLSR=AMBLQ                                                                  
=AMBLFSTP=AMBLQ                                                                 
=AMBLUBF=AMBLQ                                                                  
=AMBLKSDS=AMBLQ                                                                 
=AMBLESDS=AMBLQ                                                                 
=AMBLDFR=AMBLQ                                                                  
=AMBLPATH=AMBLTYPE                                                              
=AMBLUPGR=AMBLTYPE                                                              
=AMBLAIX=AMBLTYPE                                                               
=AMBLBASE=AMBLTYPE                                                              
=AMBLFIX=AMBLTYPE                                                               
=AMBLPRIM=AMBLSHAR                                                              
=AMBLCATO=AMBLSHAR                                                              
=AMBLWRIT=AMBLSHAR                                                              
=AMBLFULL=AMBLFLG1                                                              
=AMBLCINV=AMBLFLG1                                                              
=AMBLUPD=AMBLFLG1                                                               
=AMBLVVIC=AMBLFLG1                                                              
=AMBLSDS=AMBLFLG1                                                               
=AMBLSCRA=AMBLFLG1                                                              
=AMBLUCRA=AMBLFLG1                                                              
=AMBLCAT=AMBLFLG1                                                               
=AMBLDUMY=AMBLFLG1                                                              
=AMBLSTAG=AMBLFLG2                                                              
=BUFCUPG=BUFCFLG1                                                               
=BUFCSEG=BUFCFLG1                                                               
=BUFCINS=BUFCFLG1                                                               
=BUFCER1=BUFCFLG1                                                               
=BUFCER2=BUFCFLG1                                                               
=BUFCVAL=BUFCFLG1                                                               
=BUFCEXC=BUFCFLG1                                                               
=BUFCEPT=BUFCFLG1                                                               
=BUFCMW=BUFCIOFL                                                                
=BUFCFMT=BUFCIOFL                                                               
=BUFCRRD=BUFCIOFL                                                               
=BUFCREAL=BUFCIOFL                                                              
=BUFCWC=BUFCIOFL                                                                
=BUFCXEDB=BUFCIOFL                                                              
=BUFCPFCP=BUFCIOFL                                                              
=BUFCFIX=BUFCIOFL                                                               
=BUFCXDDR=BUFCFLG2                                                              
=BUFCNLAS=BUFCFLG2                                                              
=BUFCBSYR=BUFCFLG2                                                              
=BUFCBSYW=BUFCFLG2                                                              
=RPLLOC=RPLOPT1                                                                 
=RPLDIR=RPLOPT1                                                                 
=RPLSEQ=RPLOPT1                                                                 
=RPLSKP=RPLOPT1                                                                 
=RPLASY=RPLOPT1                                                                 
=RPLKGE=RPLOPT1                                                                 
=RPLGEN=RPLOPT1                                                                 
=RPLECBSW=RPLOPT1                                                               
=RPLECBIN=RPLOPT1                                                               
=RPLKEY=RPLOPT2                                                                 
=RPLADR=RPLOPT2                                                                 
=RPLADD=RPLOPT2                                                                 
=RPLCNV=RPLOPT2                                                                 
=RPLBWD=RPLOPT2                                                                 
=RPLLRD=RPLOPT2                                                                 
=RPLWAITX=RPLOPT2                                                               
=RPLUPD=RPLOPT2                                                                 
=RPLNSP=RPLOPT2                                                                 
=RPLEODS=RPLOPT3                                                                
=RPLSFORM=RPLOPT3                                                               
=RPLBLK=RPLOPT3                                                                 
=RPLVFY=RPLOPT3                                                                 
=RPLFLD=RPLOPT3                                                                 
=RPLFMT=RPLOPT3                                                                 
=RPLFRMT=RPLOPT3                                                                
=RPLALIGN=RPLOPT3                                                               
=RPLENDTR=RPLOPT4                                                               
=RPLMKFRM=RPLOPT4                                                               
=RPLCTA=RPLOPT4                                                                 
=RPLCTM=RPLOPT4                                                                 
=RPLCTO=RPLOPT4                                                                 
=PLHEOVW=PLHFLG1                                                                
=PLHENDRQ=PLHFLG1                                                               
=PLHASKBF=PLHFLG1                                                               
=PLHSSR=PLHFLG1                                                                 
=PLHRDEXC=PLHFLG1                                                               
=PLHASYRQ=PLHFLG1                                                               
=PLHDRPND=PLHFLG1                                                               
=PLHSRBSG=PLHFLG3                                                               
=PLHSRINV=PLHEFLGS                                                              
=PLHSR=PLHFLG1                                                                  
=PLHUPD=PLHFLG2                                                                 
=PLHSQINS=PLHFLG2                                                               
=PLHKEYMD=PLHFLG2                                                               
=PLHADDTE=PLHFLG2                                                               
=PLHKRE=PLHFLG2                                                                 
=PLHCIINS=PLHFLG2                                                               
=PLHSVADV=PLHFLG2                                                               
=PLHIWAIT=PLHFLG2                                                               
=PLHNOSPC=PLHEFLGS                                                              
=PLH1ST=PLHEFLGS                                                                
=PLHSKPER=PLHEFLGS                                                              
=PLHNOADV=PLHEFLGS                                                              
=PLHEODX=PLHEFLGS                                                               
=PLHINVAL=PLHEFLGS                                                              
=PLHDSCAN=PLHEFLGS                                                              
=PLHRSTRT=PLHEFLGS+1                                                            
=PLHRAHD=PLHFLG3                                                                
=PLHSLVLD=PLHFLG3                                                               
=PLHBWD=PLHFLG3                                                                 
=PLHRVRS=PLHFLG3                                                                
=PLHEOVDF=PLHFLG3                                                               
=PLHDRLM=PLHAFLGS                                                               
=PLHIOSRQ=PLHAFLGS                                                              
=PLHVAMB=PLHAFLGS                                                               
=PLHDBDC=PLHAFLGS                                                               
=PLHIOSID=PLHAFLGS                                                              
=PLHRABWD=PLHAFLGS                                                              
=PLHRAE=PLHAFLGS                                                                
=PLHJGET=PLHJCODE                                                               
=PLHJPUT=PLHJCODE                                                               
=PLHJERS=PLHJCODE                                                               
=PLHJRBAC=PLHJCODE                                                              
=PLHJCAS=PLHJCODE                                                               
=PLHJIER=PLHJCODE                                                               
=PLHJOER=PLHJCODE                                                               
=PLHJIXM=PLHJCODE                                                               
=PLHRSRSG=PLHJCODE                                                              
=PLHWSRSG=PLHJCODE                                                              
=PLHUWAIT=PLHUCODE                                                              
=PLHINEOV=PLHRSCS                                                               
=PLHBUFHD=PLHRSCS                                                               
=PLHASYER=PLHRSCS                                                               
=PLHDSERR=PLHRSCS                                                               
=PLHDBPER=PLHRSCS                                                               
+         IDAAMBXN ,                                           IDAAMBXN         
+         IDAAMBL  ,                                           IDAAMBL          
+         IDAAMB   ,                                           IDAAMB           
+         IFGRPL   ,                                           IFGRPL           
+         IDAIOMB  ,                                           IOMB             
+         IDAPLH   ,                                           IDAPLHD          
+         IEZCTGFL ,                                           CTGFL            
+         IDAIXH   ,                                           IDAIXH           
+         IDABUFD  ,                                           IDABUFDR         
+         IDABUFC  ,                                           IDABUFC          
+         IFGACB   ,                                           IFGACB           
