CSD                                                                             
FRRS=FRRS                                                                       
IOS=IOSB                                                                        
LCCA                                                                            
PCCAT00P=PCCAVT                                                                 
PCCAVT                                                                          
PCCA                                                                            
PWA                                                                             
SDWA                                                                            
-FRRSRMRT                                                                       
-FRRSALOC                                                                       
-FRRSAREA                                                                       
-FRRSAVE                                                                        
-FRRSQA                                                                         
-FRRSCDPT                                                                       
-FRRSALLC                                                                       
-FRRSRBPT                                                                       
-FRRSTNSM                                                                       
-FRRSTPRS                                                                       
-FRRSIGP                                                                        
-FRRSYMSK                                                                       
-FRRSUCB                                                                        
-FRRSAPTR                                                                       
-FRRSVR14                                                                       
-IOSGENSB                                                                       
-IOSBPTR                                                                        
-IOSBYTE                                                                        
-IOSCCHH                                                                        
-IOSVAIA                                                                        
-LCCAPTR                                                                        
-PCCAPTR                                                                        
-SDWAWHERE                                                                      
-SDWADDR                                                                        
-SDWAPTR                                                                        
=CSDMP=CSDFLAGS                                                                 
=FRRSNEST=FRRSFLG1                                                              
=FRRSRCUR=FRRSFLG1                                                              
=IOSDIESE=IOSFLB                                                                
=IOSEQCHK=IOSSNS                                                                
=IOSPCHKB=IOSTSB                                                                
=IOSPGDPX=IOSPKEY                                                               
=IOSSMDB=IOSFLA                                                                 
=IOSECB3=IOSCOD                                                                 
=IOSECB7=IOSCOD                                                                 
=IOSIDR=IOSPKEY                                                                 
=IOSMSG=IOSFLB                                                                  
=IOSERR=IOSFLA                                                                  
=IOSLOG=IOSFLB                                                                  
=IOSBYP=IOSOPT                                                                  
=IOSEX=IOSFLA                                                                   
=IOSFP=IOSSNS+1                                                                 
=IOSM=IOSEEK                                                                    
=LCCAPDAT=LCCAIHR1                                                              
=LCCACRIN=LCCACREX                                                              
=LCCACREF=LCCACREX                                                              
=LCCACRST=LCCACREX                                                              
=LCCACRLM=LCCACREX                                                              
=LCCACLMS=LCCACRFL                                                              
=LCCACRTM=LCCACRFL                                                              
=LCCACRRT=LCCACREX                                                              
=LCCACRLE=LCCACREX                                                              
=LCCAVARY=LCCACRFL                                                              
=LCCACRRM=LCCACREX                                                              
=LCCAEXSN=LCCASPN1                                                              
=LCCARSTR=LCCASPN1                                                              
=LCCAPTLB=LCCASPN1                                                              
=LCCASRBM=LCCADSF2                                                              
=LCCATSPN=LCCASPN1                                                              
=LCCATIMR=LCCADSF1                                                              
=LCCAACR=LCCADSF1                                                               
=PCCACALT=PCCACHS2                                                              
=PCCACCHA=PCCACHBL                                                              
=PCCACCHV=PCCACHVA                                                              
=PCCACCMD=PCCACHVA                                                              
=PCCACCNT=PCCACHPF                                                              
=PCCACCPU=PCCACHBL                                                              
=PCCACCRA=PCCACHS2                                                              
=PCCACCUE=PCCACHBL                                                              
=PCCACDAV=PCCACHVA                                                              
=PCCACFRR=PCCACHS1                                                              
=PCCACF11=PCCACHF1                                                              
=PCCACF12=PCCACHF1                                                              
=PCCACF13=PCCACHF1                                                              
=PCCACF14=PCCACHF1                                                              
=PCCACF16=PCCACHF1                                                              
=PCCACF23=PCCACHF2                                                              
=PCCACF24=PCCACHF2                                                              
=PCCACF25=PCCACHF2                                                              
=PCCACF26=PCCACHF2                                                              
=PCCACF27=PCCACHF2                                                              
=PCCACF28=PCCACHF2                                                              
=PCCACHIB=PCCACHRB                                                              
=PCCACIBC=PCCACHS1                                                              
=PCCACINB=PCCACHRB                                                              
=PCCACINT=PCCACHPF                                                              
=PCCACIOR=PCCACHS2                                                              
=PCCACMOD=PCCACHS2                                                              
=PCCACNLG=PCCACHS2                                                              
=PCCACNLS=PCCACHS1                                                              
=PCCACNOR=PCCACHPF                                                              
=PCCACNRE=PCCACHS1                                                              
=PCCACSCU=PCCACHBL                                                              
=PCCACSIB=PCCACHRB                                                              
=PCCACSQV=PCCACHVA                                                              
=PCCACSTG=PCCACHBL                                                              
=PCCACTIB=PCCACHRB                                                              
=PCCACUCB=PCCACHS1                                                              
=PCCACUNS=PCCACHVA                                                              
=PCCACURC=PCCACHS2                                                              
=PCCAISRB=PCCACHF3                                                              
=PCCASYNC=PCCATMFL                                                              
=PCCASLCK=PCCACHF3                                                              
=PCCANUCC=PCCACCE                                                               
=PCCANUTD=PCCATODE                                                              
=PCCANFCC=PCCACCE                                                               
=PCCANFTD=PCCATODE                                                              
=PCCANFIN=PCCAINTE                                                              
=PCCAINIT=PCCATMFL                                                              
=PCCANUIN=PCCAINTE                                                              
=PCCAMINT=PCCATMFL                                                              
=PCCAVKIL=PCCATMFL                                                              
=PCCARMS=PCCARMSB                                                               
=PCCAMCC=PCCATMFL                                                               
=PCCAIO=PCCAATTR                                                                
=SDWACLUP=SDWAERRD                                                              
=SDWAERFL=SDWAERRD                                                              
=SDWADLST=SDWADPFS                                                              
=SDWAFLLK=SDWAACF4                                                              
=SDWAFREE=SDWAACF2                                                              
=SDWALDIS=SDWAERRB                                                              
=SDWAMCHK=SDWAERRA                                                              
=SDWAMCIV=SDWAERRD                                                              
=SDWAPCHK=SDWAERRA                                                              
=SDWAPERC=SDWAERRC                                                              
=SDWARCRD=SDWAACF2                                                              
=SDWARKEY=SDWAERRA                                                              
=SDWARPIV=SDWAERRD                                                              
=SDWASALL=SDWAACF3                                                              
=SDWASPIN=SDWAACF2                                                              
=SDWASRBM=SDWAERRB                                                              
=SDWASTAF=SDWAERRC                                                              
=SDWASVCE=SDWAERRA                                                              
=SDWATEXC=SDWAERRA                                                              
=SDWATYP1=SDWAERRB                                                              
=SDWAUPRG=SDWAACF2                                                              
=SDWADISP=SDWAACF3                                                              
=SDWACMS=SDWAACF4                                                               
=SDWAREQ=SDWACMPF                                                               
=SDWAEAS=SDWAERRC                                                               
=SDWAHEX=SDWADPVA                                                               
=SDWAIO2=SDWAEMK2                                                               
=SDWAEBC=SDWADPVA                                                               
+         IECDIOSB ,                                           IOSB             
+IOSEQCHK EQU      X'10'        IOSSNS                         IOSB             
+IOSFP    EQU      X'04'        IOSSNS+1   FILE PROTECT        IOSB             
+IOSPCHKB EQU      X'10'        IOSTSB     PROTECTION CHECK    IOSB             
+         IGFPWA   ,                                           PWA              
+         IHACSD   ,                                           CSD              
+         IHAFRRS  ,                                           FRRS             
+         IHALCCA  ,                                           LCCA             
+         IHAPCCAT ,                                           PCCAVT           
+         IHAPCCA  ,                                           PCCA             
+         IHASDWA  ,                                           SDWA             
